# Stage 1 - npm build 
FROM node:10 as build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Stage 2 - prod image creation
FROM nginx:latest
COPY --from=build /app/build /usr/share/nginx/html
