version: '3'

services:
  react_portfolio:
    image: mrplum/react_portfolio:latest
    container_name: react_portfolio
    restart: always
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.react_portfolio.frontend.rule=Host: new.sadanmallhi.com"
      - "traefik.react_portfolio.ports=9001"

networks:
  web:
    external: true
