version: '3'

services:
  react_portfolio:
    image: mrplum/react_portfolio:latest
    container_name: react_portfolio
    restart: always
    ports:
       - "9002:80"
    networks:
      - web
    labels:
      - "traefik.http.routers.react_portfolio.rule=Host(`new.sadanmallhi.com`)"
      - "traefik.http.routers.react_portfolio.tls.certResolver=sadans-acme-resolver"
      - "traefik.http.services.react_portfolio.loadbalancer.server.port=80"
networks:
  web:
    external: true
